services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: api
    ports:
      - "9000:9000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo

  front:
    build: ./front
    container_name: front
    ports:
      - "5173:80"
    env_file:
      - ./front/.env
    depends_on:
      - api

volumes:
  mongo_data:
